---
- hosts: all
  sudo: true
  gather_facts: false

  vars_files:
    - "../ansible.plone_server/defaults/main.yml"
    - "../defaults/main.yml"
    - "../hosts/port_base.yml"
    - "../hosts/{{ host }}-vars.yml"

  tasks:

    ### Create Plone zeocluster and Plone site #################################

    - include: ../ansible.plone_server/tasks/main.yml
      tags:
        - plone

    - name: Ensure always-checkout = true
      lineinfile:
        dest={{ plone_target_path }}/{{ plone_instance_name }}/buildout.cfg
        insertafter='^auto-checkout.*'
        line='always-checkout = true'
      tags:
        - plone
        - buildout

    # add passwd just in case
    - name: Ensure that admin user is created
      command: bin/client_reserved adduser admin {{ plone_initial_password }}
      args:
        chdir: "{{ plone_target_path }}/{{ plone_instance_name }}"
      sudo_user: plone_daemon
      tags:
        - plone

    ### nginx site #############################################################

    - name: Add to sites-available
      template:
        src=../templates/nginx-site.conf.j2
        dest=/etc/nginx/sites-available/{{ host }}.conf
      notify: restart nginx
      tags:
        - nginx

    - name: Add to sites-enabled
      file:
        src=/etc/nginx/sites-available/{{ host }}.conf
        dest=/etc/nginx/sites-enabled/{{ host }}.conf
        state=link
      notify: restart nginx
      tags:
        - nginx

    ### varnish site ###########################################################

    - name: Add varnish site configuration
      template:
        src=../templates/varnish-site.vcl.j2
        dest=/etc/varnish/sites/{{ host }}.vcl
      notify: restart varnish
      tags:
        - varnish

    - name: add site include to sites.vcl
      lineinfile:
        dest=/etc/varnish/sites.vcl
        regexp='.*{{ host }}.*'
        insertbefore=BOF
        line='include "/etc/varnish/sites/{{ host }}.vcl";'
      tags:
        - varnish

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

    - name: restart varnish
      service: name=varnish state=restarted


