---
- hosts: all
  sudo: true
  gather_facts: false

  vars_files:
    - "../defaults/server-setup.yml"
    - "../host_vars/{{ inventory_hostname }}"

  tasks:

    ### Bika dependencies ######################################################

    - name: Bika dependencies - Install
      apt: pkg={{ item }} state=present
      with_items:
        - libffi-dev
        - gcc
        - zlib1g-dev
        - libexpat1-dev
        - libxslt1.1
        - gnuplot
        - libpcre3
        - libpcre3-dev
        - libcairo2
        - libpango1.0-0
        - libgdk-pixbuf2.0-0
        - ssl-cert
        - nginx
        - varnish
        - munin
        - munin-node

    ### nginx server ###########################################################

    - name: nginx - Install
      apt: pkg=nginx state=present

    - name: nginx - /etc/nginx/proxy_params.conf
      template:
        src=../templates/nginx-proxy_params.conf.j2
        dest=/etc/nginx/proxy_params.conf

    ### varnish server #########################################################

    - name: varnish - /etc/varnish/default.vcl
      template:
        src=../templates/varnish-default.vcl.j2
        dest=/etc/varnish/default.vcl

    - name: create varnish/sites folder
      file: path=/etc/varnish/sites state=directory

    - name: create varnish/sites.vcl
      copy: src=../templates/sites.vcl.j2 dest=/etc/varnish/sites.vcl force=no
