---
- hosts: all
  sudo: true
  gather_facts: false

  vars_files:
    - "../ansible.plone_server/defaults/main.yml"
    - "../defaults/main.yml"
    - "../host_vars/{{ inventory_hostname }}"

  tasks:

    - name: Supervisor zeoserver started
      supervisorctl:
        name={{ supervisor_instance_name or ''}}zeoserver
        state=started

    - name: Supervisor zeoclient tasks are started
      supervisorctl:
        name={{ supervisor_instance_name or ''}}zeoclient{{ item }}
        state=started
      with_sequence: count={{ plone_client_count }}
