---
- hosts: all
  sudo: true
  gather_facts: false

  vars_files:
    - "../ansible.plone_server/defaults/main.yml"
    - "../defaults/main.yml"
    - "../port_base.yml"
    - "../host_vars/{{ inventory_hostname }}"

  tasks:

    - name: Copy buildout template
      when: not plone_buildout_git_repo
      template:
        src=../ansible.plone_server/templates/buildout.cfg.j2
        dest={{ plone_target_path }}/{{ plone_instance_name }}/buildout.cfg
        owner=plone_buildout
        group=plone_group
        backup=yes
      register: instance_status

    - name: Ensure always-checkout = force
      lineinfile:
        dest="{{ plone_target_path }}/{{ plone_instance_name }}/buildout.cfg"
        insertafter="^auto-checkout.*"
        line="always-checkout = force"
      tags:
        - plone

    - name: Run buildout
      command: bin/buildout
        chdir={{ plone_target_path }}/{{ plone_instance_name }}
      sudo_user: plone_buildout

    - name: Everything in buildout cache is group-readable
      command: chmod -R g+r,o+r {{ plone_target_path }}/buildout-cache

    - name: Check if bin/develop exists
      stat: path={{ plone_target_path }}/{{ plone_instance_name }}/bin/develop
      register: develop

    - name: Update sources
      sudo_user: plone_buildout
      command: bin/develop update
      when: develop.stat.exists
      args:
        chdir: "{{ plone_target_path }}/{{ plone_instance_name }}"

    - name: restart zeoclients
      supervisorctl:
        name={{ supervisor_instance_name or ''}}zeoclient{{ item }}
        state=restarted
      with_sequence: count={{ plone_client_count }}
        - update
        - restart
