---
- hosts: all
  sudo: true
  gather_facts: false

  vars_files:
    - "../ansible.plone_server/defaults/main.yml"
    - "../defaults/main.yml"
    - "../host_vars/{{ inventory_hostname }}"

  tasks:

    - name: Update sources
      sudo_user: plone_buildout
      command: bin/develop update
      args:
        chdir: "{{ plone_target_path }}/{{ plone_instance_name }}"
      tags:
        - update
        - sources

    - name: Run buildout
      sudo_user: plone_buildout
      command: bin/buildout
      args:
        chdir: "{{ plone_target_path }}/{{ plone_instance_name }}"
      tags:
        - update
        - buildout

    - name: restart zeoclients
      supervisorctl:
        name={{ supervisor_instance_name or ''}}zeoclient{{ item }}
        state=restarted
      with_sequence: count={{ plone_client_count }}
        - update
        - restart
